# Generated by Django 3.1.7 on 2021-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
