# Generated by Django 3.1.7 on 2021-03-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210321_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='confirm email token'),
        ),
    ]
