# Generated by Django 3.1.7 on 2021-03-26 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import transactions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pocket', '0003_pocket_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_created=True, verbose_name='date created')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('sum', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='sum')),
                ('action', models.PositiveIntegerField(choices=[('REFILL', 1), ('DEBIT', 2)], verbose_name='action')),
                ('status', models.PositiveIntegerField(choices=[('CREATED', 1), ('IN_PROCESS', 2), ('FINISHED', 3), ('CANCELLED', 4)], default=transactions.models.TransactionStatus['CREATED'], verbose_name='status')),
                ('data_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pocket.pocket', verbose_name='Pocket')),
            ],
        ),
    ]
