# Generated by Django 3.1.7 on 2021-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pockettransaction',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
