# Generated by Django 3.1.7 on 2021-03-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210326_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pockettransaction',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='pockettransaction',
            old_name='data_updated',
            new_name='date_updated',
        ),
    ]
