# Generated by Django 3.1.7 on 2021-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210327_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pockettransaction',
            name='action',
            field=models.PositiveIntegerField(choices=[(1, 'REFILL'), (2, 'DEBIT')], verbose_name='action'),
        ),
    ]
